CompanyBudgetTracker/Controllers/CostIncomeController.cs
using System.Diagnostics;
using CompanyBudgetTracker.Context;
using CompanyBudgetTracker.Models;
using CompanyBudgetTracker.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System;
using System.Threading.Tasks;
using CompanyBudgetTracker.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CompanyBudgetTracker.Controllers;

public class CostIncomeController : BaseController
{
    private readonly ILogger<CostIncomeController> _logger;
    private readonly MyDbContext _context;
    private readonly ICostIncomeService _costIncomeService;
    private readonly ICurrentUserService _currentUserService;

    public CostIncomeController(
        ILogger<CostIncomeController> logger,
        MyDbContext context,
        ICostIncomeService costIncomeService,
        ICurrentUserService currentUserService) : base(context, currentUserService)
    {
        _logger = logger;
        _context = context;
        _costIncomeService = costIncomeService;
        _currentUserService = currentUserService;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult RedirectToNewRecord()
    {
        var categories = _context.Categories
            .Select(c => new { c.Id, c.Name })
            .ToList();

        ViewData["Categories"] = new SelectList(categories, "Id", "Name");

        return View("NewRecord");
    }

    public async Task<IActionResult> GetHistory(string? itemName, int? itemId, string? itemType, DateTime? startDate, DateTime? endDate, string? sortOrder, int page = 1, int pageSize = 10)
    {
        var userId = _currentUserService.GetUserId();
        ViewBag.IdSortParm = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
        ViewBag.NameSortParm = sortOrder == "name_asc" ? "name_desc" : "name_asc";
        ViewBag.TypeSortParm = sortOrder == "type_asc" ? "type_desc" : "type_asc";
        ViewBag.AmountSortParm = sortOrder == "amount_asc" ? "amount_desc" : "amount_asc";
        ViewBag.DateSortParm = sortOrder == "date_asc" ? "date_desc" : "date_asc";

        var query = _context.CostIncomes.AsQueryable();
        if (!User.IsInRole("Admin")) {
            query = query.Where(x => x.UserId == userId);
        }

        if (itemId.HasValue)
            query = query.Where(x => x.Id == itemId.Value);
        if (!string.IsNullOrWhiteSpace(itemName))
            query = query.Where(x => x.Name.Contains(itemName));
        if (!string.IsNullOrWhiteSpace(itemType))
            query = query.Where(x => x.Type.Contains(itemType));
        if (startDate.HasValue)
            query = query.Where(x => x.Date >= startDate.Value);
        if (endDate.HasValue)
            query = query.Where(x => x.Date <= endDate.Value);

        query = sortOrder switch {
            "date_asc" => query.OrderBy(x => x.Date),
            "amount_desc" => query.OrderByDescending(x => x.Amount),
            "name_desc" => query.OrderByDescending(x => x.Name),
            "name_asc" => query.OrderBy(x => x.Name),
            _ => query.OrderByDescending(x => x.Id),
        };

        int totalRecords = await query.CountAsync();
        var records = await query.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

        ViewData["TotalRecords"] = totalRecords;
        ViewData["CurrentPage"] = page;
        ViewData["PageSize"] = pageSize;
        ViewData["TotalPages"] = (int)Math.Ceiling(totalRecords / (double)pageSize);

        return View("History", records);
    }

    [HttpPost]
    public async Task<IActionResult> SaveTransaction(CostIncomeModel viewModel, IFormFile transactionAtt)
    {
        var userId = _currentUserService.GetUserId();
        viewModel.UserId = userId;

        if (transactionAtt != null && transactionAtt.Length > 0)
        {
            using (var memoryStream = new MemoryStream())
            {
                await transactionAtt.CopyToAsync(memoryStream);
                viewModel.Attachment = memoryStream.ToArray();
                viewModel.AttachmentName = transactionAtt.FileName;
                viewModel.AttachmentContentType = transactionAtt.ContentType;
            }
        }
        
        if (!_context.Categories.Any(c => c.Id == viewModel.CategoryId))
        {
            ModelState.AddModelError("CategoryId", "Selected category is invalid.");
        }
        
        if (ModelState.IsValid)
        {
            await _costIncomeService.SaveAsync(viewModel);
            return RedirectToAction("Index");
        }
        
        var errors = ModelState
            .Where(x => x.Value.Errors.Count > 0)
            .SelectMany(x => x.Value.Errors)
            .Select(e => e.ErrorMessage).ToList();
        
        ViewBag.Errors = errors;
        return View("NewRecord", viewModel);
    }

    
    [HttpPost]
    public async Task<IActionResult> DeleteTransaction(int id)
    {
        try
        {
            await _costIncomeService.DeleteAsync(id);
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            _logger.LogError($"Error deleting transaction with ID {id}: {ex}");
            return View("Error");
        }
    }
    
    public IActionResult OpenAttachment(int attachmentId)
    {
        var attachment = _context.CostIncomes.FirstOrDefault(x => x.Id == attachmentId);
        if (attachment == null)
        {
            return NotFound();
        }

        return File(attachment.Attachment, attachment.AttachmentContentType, attachment.AttachmentName);
    }

    public async Task<IActionResult> Details(int? itemId)
    {
        if (!itemId.HasValue)
        {
            return NotFound();
        }

        var userId = _currentUserService.GetUserId();
        var record = await _context.CostIncomes
            .FirstOrDefaultAsync(m => m.Id == itemId.Value && (m.UserId == userId || User.IsInRole("Admin")));
        
        if (record == null)
        {
            return NotFound();
        }

        return View("RecordDetails", record);
    }

    public async Task<IActionResult> Settle(int itemId, bool settled)
    {
        var record = _context.CostIncomes.FirstOrDefault(x => x.Id == itemId);
        
        if (itemId == null)
        {
            return NotFound();
        }

        await _costIncomeService.UpdateSettledStatusAsync(itemId, settled);

        return View("Index");
    }

    public async Task<IActionResult> DeleteRecord(int itemId)
    {
        if (itemId == null)
        {
            return NotFound();
        }

        await _costIncomeService.DeleteAsync(itemId);

        return View("Index");
    }
    
}

CompanyBudgetTracker/Views/CostIncome/History.cshtml
@using CompanyBudgetTracker.Controllers
@model IEnumerable<CompanyBudgetTracker.Models.CostIncomeModel>

@{
    ViewData["Title"] = "Cost / Income history";
}

<h2>@ViewData["History"]</h2>

<form method="get" action="@Url.Action("GetHistory", "CostIncome")">
    <div class="form-group">
        <div class="filtering-class">
            <label for="itemId">ID:</label>
            <input type="number" id="itemId" name="itemId" class="form-control"/>
            <label for="itemName">Name:</label>
            <input type="text" id="itemName" name="itemName" class="form-control"/>
            <label for="itemType">Type:</label>
            <input type="text" id="itemType" name="itemType" class="form-control"/>
            <label for="startDate">Start Date:</label>
            <input type="date" id="startDate" name="startDate" class="form-control"/>
            <label for="endDate">End Date:</label>
            <input type="date" id="endDate" name="endDate" class="form-control"/>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Filter</button>
    <button type="submit" class="btn btn-primary">Clear filters</button>
</form>

<table class="table">
    <thead>
    <tr>
        <th>
            <a href="@Url.Action("GetHistory", "CostIncome", new { sortOrder = ViewBag.IdSortParm })">ID</a>
        </th>
        <th>
            <a href="@Url.Action("GetHistory", "CostIncome", new { sortOrder = ViewBag.NameSortParm })">Name</a>
        </th>
        <th>
            <a href="@Url.Action("GetHistory", "CostIncome", new { sortOrder = ViewBag.TypeSortParm })">Type</a>
        </th>
        <th>
            <a href="@Url.Action("GetHistory", "CostIncome", new { sortOrder = ViewBag.AmountSortParm })">Amount</a>
        </th>
        <th>
            <a href="@Url.Action("GetHistory", "CostIncome", new { sortOrder = ViewBag.DateSortParm })">Date</a>
        </th>
        <th>AttachmentName</th>
        <th>AttachmentContentType</th>
        <th>Settled</th>
        <th>Details</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var record in Model)
    {
        <tr>
            <td>@record.Id</td>
            <td>@record.Name</td>
            <td>@record.Type</td>
            <td>@record.Amount</td>
            <td>@record.Date.ToShortDateString()</td>
            <td>@record.AttachmentName</td>
            <td>@record.AttachmentContentType</td>
            <td>@record.Settled</td>
            <td>
                <a href="@Url.Action("Details", "CostIncome", new { itemId = record.Id })" class="btn btn-info">Details</a>
            </td>
            <td>
                @if (!record.Settled)
                {
                    <a href="@Url.Action("Settle", "CostIncome", new { itemId = record.Id, settled = true })"
                       class="btn btn-primary"> Settle </a>
                }
                else
                {
                    <button class="btn btn-primary" disabled>Settle</button>
                }
            </td>
            <td>
                <a href="@Url.Action("DeleteRecord", "CostIncome", new { itemId = record.Id })"
                   id="deleteBtn" class="btn btn-primary"> Delete </a>
            </td>
        </tr>
    }
    <tr>
        <td colspan="7" style="text-align: right;"><strong>Total:</strong></td>
        <td>@ViewData["TotalAmount"]</td>
    </tr>
    </tbody>
</table>

<nav aria-label="Page navigation example">
    <ul class="pagination">
        <li class="page-item @((int)ViewData["CurrentPage"] == 1 ? "disabled" : "")">
            <a class="page-link" href="@Url.Action("GetHistory", new { page = (int)ViewData["CurrentPage"] - 1 })">Previous</a>
        </li>
        @for (int i = 1; i <= (int)ViewData["TotalPages"]; i++)
        {
            <li class="page-item @(i == (int)ViewData["CurrentPage"] ? "active" : "")">
                <a class="page-link" href="@Url.Action("GetHistory", new { page = i })">@i</a>
            </li>
        }
        <li class="page-item @(ViewData["CurrentPage"].ToString() == ViewData["TotalPages"].ToString() ? "disabled" : "")">
            <a class="page-link" href="@Url.Action("GetHistory", new { page = (int)ViewData["CurrentPage"] + 1 })">Next</a>
        </li>
    </ul>
</nav>

<style>
    .filtering-class {
        display: flex;
        align-items: center;
        gap: 10px;
    }
</style>

CompanyBudgetTracker/Views/CostIncome/Index.cshtml
@{
    ViewData["Title"] = "Costs and Incomes";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <a href="@Url.Action("RedirectToNewRecord", "CostIncome")" class="btn btn-secondary">Add New Cost / Income</a>
    <a href="@Url.Action("GetHistory", "CostIncome")" class="btn btn-secondary">View History</a>
</div>
@section Scripts
{
    <script type="text/javascript">
        document.getElementById('deleteRecordBtn').addEventListener('click', function () {
            window.location.href = '@Url.Action("DeleteRecord", "CostIncome")'
        });
    </script>
    <script type="text/javascript">
        document.getElementById('addRecordBtn').addEventListener('click', function () {
            window.location.href = '@Url.Action("RedirectToNewRecord", "CostIncome")'
        });
    </script>
    <script type="text/javascript">
        document.getElementById('viewHistoryBtn').addEventListener('click', function () {
            window.location.href = '@Url.Action("GetHistory", "CostIncome")'
        });
    </script>
}

CompanyBudgetTracker/Views/CostIncome/Manager.cshtml
@using CompanyBudgetTracker.Controllers
@model IEnumerable<CompanyBudgetTracker.Models.CostIncomeModel>

@{
    ViewData["Title"] = "Cost / Income history";
}

<h2>@ViewData["History"]</h2>

<form method="get" action="@Url.Action("GetHistory", "CostIncome")">
    <div class="form-group">
        <div class="filtering-class">
            <label for="itemId">ID:</label>
            <input type="number" id="itemId" name="itemId" class="form-control"/>
            <label for="itemName">Name:</label>
            <input type="text" id="itemName" name="itemName" class="form-control"/>
            <label for="itemType">Type:</label>
            <input type="text" id="itemType" name="itemType" class="form-control"/>
            <label for="startDate">Start Date:</label>
            <input type="date" id="startDate" name="startDate" class="form-control"/>
            <label for="endDate">End Date:</label>
            <input type="date" id="endDate" name="endDate" class="form-control"/>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Filter</button>
    <button type="submit" class="btn btn-primary">Clear filters</button>
</form>

<table class="table">
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Type</th>
        <th>Amount</th>
        <th>Date</th>
        <th>AttachmentName</th>
        <th>AttachmentContentType</th>
        <th>Open Attachment</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var record in Model)
    {
        <tr>
            <td>@record.Id</td>
            <td>@record.Name</td>
            <td>@record.Type</td>
            <td>@record.Amount</td>
            <td>@record.Date.ToShortDateString()</td>
            <td>@record.AttachmentName</td>
            <td>@record.AttachmentContentType</td>
            <td>
                <a href="@Url.Action("OpenAttachment", "CostIncome", new { attachmentId = record.Id })" 
                   id="openAttachment" class="btn btn-primary"> Open </a> 
            </td>
            <td>
                <a href="@Url.Action("Settle", "CostIncome", new { itemId = record.Id, settled = true })" 
                   class="btn btn-primary"> Settle </a>

            </td>
        </tr>
    }
    <tr>
        <td colspan="7" style="text-align: right;"><strong>Total:</strong></td>
        <td>@ViewData["TotalAmount"]</td>
    </tr>
    </tbody>
</table>

<style>
    .filtering-class {
        display: flex;
        align-items: center;
        gap: 10px;
    }
</style>

CompanyBudgetTracker/Views/CostIncome/NewRecord.cshtml
@using CompanyBudgetTracker.Controllers
@inject CompanyBudgetTracker.Interfaces.ICurrentUserService CurrentUserService

@{
    ViewData["Title"] = "Add New Cost / Income";
}

<style>
    .form-container {
        display: grid;
        grid-template-columns: 1fr 1fr 1fr 1fr;
        grid-gap: 20px;
        align-items: center;
    }

    .form-group {
        margin-bottom: 20px;
    }

    .form-group.full-width {
        grid-column: span 4;
    }
    .form-element {
        margin-bottom: 20px;
    }
    .input-valid {
        border-color: #198754; /* Bootstrap success green */
    }
    
    .input-invalid {
        border-color: #dc3545; /* Bootstrap danger red */
    }
    
    .validation-message {
        color: #dc3545; /* Bootstrap danger red  */
        font-size: 0.875em;
    }
</style>

<form method="post" id="transactionForm" enctype="multipart/form-data" action="@Url.Action("SaveTransaction", "CostIncome")">
    <div class="text-center form-element">
        <h1 class="display-4">Welcome</h1>
        <div class="form-container">
            <div class="form-group">
                <input type="hidden" id="userId" name="UserId" value="@CurrentUserService.GetUserId()" />
                <label>Name: </label>
                <input id="transactionName" name="Name" type="text" required/>
            </div>
            
            <div class="form-group">
                <label>Amount: </label>
                <input id="amount" name="Amount" type="number" min="0.01" required/>
            </div>
            
            <div class="form-group">
                <label>Type: </label>
                <select id="transactionType" name="Type">
                    <option value="Cost">Cost</option>
                    <option value="Income">Income</option>
                </select>
            </div>

            <div class="form-group">
                <label>Date: </label>
                <input id="transactionDate" name="Date" type="date" required/>
            </div>

            <div class="form-group full-width">
                <label for="categoryId">Category: </label>
                <select id="categoryId" name="CategoryId" class="form-control" required>
                    <option value="">Please select a category</option>
                    @foreach (var category in (SelectList)ViewData["Categories"])
                    {
                        <option value="@category.Value">@category.Text</option>
                    }
                </select>
            </div>

            <div class="form-group full-width">
                <label for="transactionAtt">Select attachment (if required): </label>
                <input id="transactionAtt" name="transactionAtt" type="file" required onchange="updateLabel()"/>
            </div>
        </div>
        <div class="text-center form-element">
            <button type="submit" id="submitBtn">Submit</button>
        </div>
    </div>
</form>



@section Scripts
{
    <script type="text/javascript">
        document.getElementById("submitBtn").addEventListener("click", function (event) {
            event.preventDefault();
            
            var formData = new FormData(document.getElementById("transactionForm"));
            fetch('@Url.Action("SaveTransaction", "CostIncome")', {
                method: 'POST',
                body: formData,
            })
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                if (response.redirected) {
                    window.location.href = response.url; 
                } else {
                    return response.json();
                }
            })
            .then(data => {
                console.log('Success:', data);
            })
            .catch(error => {
                console.error('Error:', error);
            });
        });

    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            validateForm();
    
            function validateInput(inputElement, isValid) {
                if (isValid) {
                    $(inputElement).removeClass("input-invalid").addClass("input-valid");
                    $(inputElement).next(".validation-message").remove();
                } else {
                    $(inputElement).removeClass("input-valid").addClass("input-invalid");
                    if ($(inputElement).next(".validation-message").length === 0) {
                        $('<div class="validation-message">This field is required.</div>').insertAfter($(inputElement));
                    }
                }
            }
    
            function validateForm() {
                var isFormValid = true;
    
                var name = $('#transactionName').val().trim();
                validateInput('#transactionName', name !== '');
                isFormValid &= (name !== '');
    
                var amount = parseFloat($('#amount').val());
                validateInput('#amount', !isNaN(amount) && amount > 0);
                isFormValid &= (!isNaN(amount) && amount > 0);
    
                var date = $('#transactionDate').val().trim();
                validateInput('#transactionDate', date !== '');
                isFormValid &= (date !== '');
    
                var category = $('#categoryId').val().trim();
                validateInput('#categoryId', category !== '');
                isFormValid &= (category !== '');
    
                $("#submitBtn").prop('disabled', !isFormValid);
            }
    
            $("input, select").on("change keyup", function () {
                validateForm();
            });
        });
    </script>

    
}

CompanyBudgetTracker/Views/CostIncome/RecordDetails.cshtml
@model CompanyBudgetTracker.Models.CostIncomeModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Record Details</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">ID</dt>
        <dd class="col-sm-10">@Model.Id</dd>
        <dt class="col-sm-2">Name</dt>
        <dd class="col-sm-10">@Model.Name</dd>
    </dl>
    <div>
        <a href="@(Model.AttachmentName != null ? Url.Action("OpenAttachment", "CostIncome", new { attachmentId = Model.Id }) : "#")"
           class="btn btn-primary @(Model.AttachmentName != null ? "" : "disabled")"
           role="button"
           aria-disabled="@(Model.AttachmentName != null ? "false" : "true")">Download Attachment</a>
    </div>
    
    <a asp-action="GetHistory" class="btn btn-secondary">Back to List</a>
</div>